// Unit 2: original, deterministic teaching examples; no model training runs here.
const prepState={stage:0,split:'files',code:20,budget:100,trial:'controlled',revealed:false,gates:{}};
const prepDocs=[
 {id:'A',group:'sky',text:'天空为什么呈现蓝色？这篇文章解释光的散射。',raw:'首页 | 订阅 | 天空为什么呈现蓝色？这篇文章解释光的散射。 | 下一篇',kind:'正文'},
 {id:'B',group:'sky',text:'天空为什么呈现蓝色？这篇文章解释光的散射。',raw:'转载站 | 天空为什么呈现蓝色？这篇文章解释光的散射。',kind:'完全重复'},
 {id:'C',group:'sky',text:'天空为何看起来是蓝的？本文介绍光的散射现象。',raw:'科普转载 | 天空为何看起来是蓝的？本文介绍光的散射现象。',kind:'近似改写'},
 {id:'D',group:'code',text:'空列表遍历零次；循环体不会执行。',raw:'编程笔记 | 空列表遍历零次；循环体不会执行。 | 联系我们',kind:'正文'},
 {id:'E',group:'ad',text:'立即购买！立即购买！立即购买！',raw:'立即购买！立即购买！立即购买！',kind:'广告'},
 {id:'F',group:'broken',text:'� � x00 �',raw:'� � x00 �',kind:'损坏'},
 {id:'G',group:'plant',text:'薄荷喜光，但盆土不宜长期积水。',raw:'种植手记 | 薄荷喜光，但盆土不宜长期积水。',kind:'正文'},
 {id:'H',group:'repair',text:'这台风扇咋不转？先断电，再查叶片有没有卡住。',raw:'维修问答 | 这台风扇咋不转？先断电，再查叶片有没有卡住。',kind:'口语正文'}
];
const prepStages=[['原始材料','先看来源，不急着训练'],['提取正文','去掉导航，保留内容'],['过滤','排除本任务不适用的条目'],['精确去重','同一正文，只留一份']];
function preparedDocs(stage){return prepDocs.filter(d=>stage<2||!['E','F'].includes(d.id)).filter(d=>stage<3||d.id!=='B')}
function prepPipeline(){
 const docs=preparedDocs(prepState.stage),notes=[
 '8 条记录不等于 8 份独立知识。A、B 是同文转载，C 是近似改写；每条记录还应保存来源、抓取时间与使用条件。',
 '正文提取改变的是每条记录的内容，本例数量仍是 8。真实网页的代码块、表格和公式也可能被误删，需要抽样检查。',
 '本例排除 E、F，剩 6 条。H 虽然口语化，却包含有用信息，保留。过滤规则不能只把“像教科书”当成质量。',
 '本例按提取后的正文做精确比较，去掉 B，剩 5 条。C 措辞不同，因此还在。精确去重不等于近似去重；下面继续检查跨集合重叠。'];
 return `<div class="prep-stage-tabs" role="group" aria-label="数据整理步骤">${prepStages.map((s,i)=>`<button data-prep-stage="${i}" aria-pressed="${prepState.stage===i}"><small>0${i+1}</small><strong>${s[0]}</strong><span>${s[1]}</span></button>`).join('')}</div><div class="prep-stage-result" aria-live="polite"><p class="prep-count"><strong>${docs.length}</strong> / 8 条保留 · ${prepStages[prepState.stage][0]}</p><div class="prep-docs">${prepDocs.map(d=>{const kept=docs.includes(d);return `<article class="prep-doc ${kept?'':'removed'}"><span class="prep-doc-label">${d.id} · ${d.kind} ${kept?'':'· 已排除'}</span><p>${esc(prepState.stage?d.text:d.raw)}</p>${d.id==='C'&&prepState.stage===3?'<small>措辞不同，精确比较未识别</small>':''}</article>`}).join('')}</div><p class="prep-explain">${notes[prepState.stage]}</p></div>`;
}
function splitExample(mode){
 const train=mode==='files'?['A','D','G']:['A','C','D'],validation=mode==='files'?['C','H']:['G','H'];
 const overlap=[...new Set(train.map(id=>prepDocs.find(d=>d.id===id).group))].filter(g=>validation.some(id=>prepDocs.find(d=>d.id===id).group===g));
 return {train,validation,overlap};
}
function splitView(){const s=splitExample(prepState.split);return `<div class="prep-split-columns">${[['训练集',s.train,'用于计算训练信号、更新参数'],['验证集',s.validation,'用于观察表现、选择方案']].map(([label,ids,note])=>`<div><h3>${label}</h3><small>${note}</small>${ids.map(id=>{const d=prepDocs.find(d=>d.id===id);return `<p class="split-card ${d.group==='sky'?'sky-family':''}"><strong>${id} · ${d.group==='sky'?'同一文章家族':'独立材料'}</strong>${d.text}</p>`}).join('')}</div>`).join('')}</div><div class="prep-verdict ${s.overlap.length?'caution':''}"><strong>${s.overlap.length?'出现跨集合近似重叠':'本例已消除已知文章家族重叠'}</strong><p>${s.overlap.length?'训练见过 A，验证却用它的改写 C。文件不同，信息仍可能重叠；这不能当成可靠的新题检查。':'A 与 C 放在同一侧，验证使用 G、H。这里只处理了人工已知的相似家族，不代表真实语料已经没有污染。'}</p></div>`}
function mixtureMetrics(code,budget){const codeTokens=budget*code/100;return {code:codeTokens,web:budget-codeTokens,codePasses:codeTokens/20,webPasses:(budget-codeTokens)/80}}
function mixtureView(){const m=mixtureMetrics(prepState.code,prepState.budget);return `<div class="mixture-bar" role="img" aria-label="一般文本 ${100-prepState.code}%，代码 ${prepState.code}%"><span style="width:${100-prepState.code}%"></span><span style="width:${prepState.code}%"></span></div><div class="mixture-legend"><span>一般文本 ${100-prepState.code}%</span><span>代码 ${prepState.code}%</span></div><div class="prep-metric-grid">${[['一般文本',80,m.web,m.webPasses],['代码',20,m.code,m.codePasses]].map(([label,stock,tokens,passes])=>`<article><h3>${label}</h3><dl><div><dt>可用去重语料</dt><dd>${stock} M tokens</dd></div><div><dt>计划读取</dt><dd>${tokens.toFixed(0)} M tokens</dd></div><div><dt>平均遍数</dt><dd>${passes.toFixed(2)} ×</dd></div></dl><div class="exposure-cells" aria-label="每格表示约一遍，最后一格可能不足一遍">${Array.from({length:Math.ceil(passes)},(_,i)=>`<span style="opacity:${Math.min(1,passes-i)*.65+.25}">${i+1}</span>`).join('')}</div></article>`).join('')}</div><p class="prep-explain">${m.code===0?'当前代码预算为零，不读取代码；全部预算分给一般文本。':m.codePasses>1?`代码预算相当于可用代码语料的 ${m.codePasses.toFixed(2)} 遍。增加采样权重，没有凭空产生新的代码。`:'代码预算尚未超过可用代码量。若随机采样，个别片段仍可能多次出现。'} 总计划读取 ${prepState.budget} M tokens；这是 token 预算，不是 GPU 时间或费用估计。</p>`}
const ladderCases={controlled:{a:[3.2,2.8,2.6],b:[3.1,2.7,2.5],held:2.44,label:'可比较的配方对照',note:'同一列使用相同模型规模、训练 token 预算、tokenizer 和固定验证集；A、B 只改变数据配比。每列只有一次教学运行，尚未检验随机种子的波动。'},confounded:{a:[3.2,2.8,2.6],b:[2.8,2.4,2.2],held:2.15,label:'混入了更换验证集的对照',note:'B 换成更容易的验证材料。数字虽更低，却不是同一把尺；现在无法把差距归因于数据配比。'}};
function ladderEstimate(values){return values[2]-(values[1]-values[2])/2}
function ladderView(){const c=ladderCases[prepState.trial],estimate=ladderEstimate(c.b);return `<p class="prep-explain">${c.note}</p><div class="prep-table-wrap"><table class="prep-table"><caption>教学运行记录 · 所有 loss 为编造示例，越低表示该验证目标下误差越小</caption><thead><tr><th scope="col">配方</th><th scope="col">预算 1×</th><th scope="col">预算 2×</th><th scope="col">预算 4×</th></tr></thead><tbody>${[['A',c.a],['B',c.b]].map(([label,v])=>`<tr><th scope="row">${label}</th>${v.map(x=>`<td>${x.toFixed(2)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="ladder-steps" role="img" aria-label="依次用 1、2、4 倍计算预算做小实验，再检查 8 倍预算"><div style="--step:30px">1×<small>先跑通</small></div><div style="--step:55px">2×<small>看趋势</small></div><div style="--step:80px">4×<small>再比较</small></div><div class="predicted" style="--step:105px">8×<small>留作检验</small></div></div><div class="prediction-card"><span class="eyebrow">先记录预测，再看留出实验</span><p>假设 B 每次翻倍预算，loss 的改善量减半：${c.b[0].toFixed(2)} → ${c.b[1].toFixed(2)}（降 0.40）→ ${c.b[2].toFixed(2)}（降 0.20）。那么 8× 时预测再降 0.10，得到 <strong>${estimate.toFixed(2)}</strong>。</p><p class="visual-footnote">这是为讲解外推而选的算术规则，不是拟合真实 scaling law；三点也不足以验证这条规则。</p><button class="prep-action" data-reveal-ladder ${prepState.revealed?'disabled':''}>${prepState.revealed?'已展开留出结果':'查看 8× 教学实验结果 →'}</button>${prepState.revealed?`<div class="prep-verdict caution"><strong>示例结果 ${c.held.toFixed(2)} · 预测 ${estimate.toFixed(2)} · 偏差 +${(c.held-estimate).toFixed(2)}</strong><p>${prepState.trial==='controlled'?'实际示例没有完全沿着预测走。先保留原预测，检查差距是否超过预先规定的容忍范围，再调查数据、实现、随机波动与外推假设。':'即使预测接近 B 的结果，也没有修复 A、B 使用不同验证集的问题。预测是否准确、方案是否公平比较，是两个问题。'}</p></div>`:''}</div>`}
const gateItems=[['compare','比较条件与重复实验','验证集、tokenizer、预算口径一致；检查不同随机种子的波动。'],['restore','中断后的恢复演练','确认 checkpoint、优化器状态、数据位置等能按预期恢复。'],['system','接近目标规模的系统试跑','检查显存、通信、吞吐和数值稳定性，记录异常处理方式。']];
function gateSummary(){const n=gateItems.filter(([key])=>prepState.gates[key]).length;return n===3?'你已勾选三类应检查的证据。这只是学习清单，不代表系统实际通过检查，更不保证大规模运行成功。':`已标记 ${n} / 3 项。小规模 loss 更好，不能替代尚未完成的比较与系统检查。`}
Object.assign(unitQuestions,{
 '4-clean':{question:'提取正文以后，网页条数没变，是否说明这一步没用？',options:['没用，只有数量减少才算清洗','不一定，单条内容可能已经更适合训练','说明已完成全部质量检查'],correct:1,explanations:['数量只反映一部分变化，导航噪声可能已被移除。','对。提取改变记录内容；还要抽样检查正文有没有误删。','提取不能替代来源检查、过滤、去重与污染检查。']},
 '4-leak':{question:'A 文章进训练集，它的改写 C 进验证集。文件名不同，是否足够？',options:['足够，按文件拆分就独立了','不够，要检查内容与来源家族的重叠','把 C 再复制一遍就能更稳'],correct:1,explanations:['文件不同不代表内容独立，模型可能见过相似信息。','对。应检查精确与近似重叠，并结合任务决定划分粒度。','复制不会消除泄漏，反而改变验证权重。']},
 '4-quality':{question:'过滤器把全部口语问答都删了，剩下的文字更正式。就能认定质量更好吗？',options:['能，正式语言总是更有价值','不能，要看任务需要和被误删的材料','能，数据越少越干净'],correct:1,explanations:['语言风格不是通用质量分数，口语也可能包含有效信息。','对。抽查保留与排除样本，检查过滤是否损害覆盖。','条数减少本身不能证明内容更有用。']},
 '5-stock':{question:'代码只占可用语料 20%，能分到训练 token 预算的 50% 吗？',options:['不能，库存比例决定训练比例','能，通过采样权重，但要检查重复曝光','能，而且自动产生更多独立代码'],correct:1,explanations:['库存和读取计划是两个不同的量。','对。提高权重增加读取机会，也可能更频繁读到同一材料。','加大采样权重不会创造新内容。']},
 '5-loss':{question:'换配比后训练 loss 从 2.8 降到 2.4，就能判定模型能力更强吗？',options:['能，所有 loss 都可直接比较','不能，材料难度改变也可能导致下降','不能，因为重复数据永远有害'],correct:1,explanations:['训练目标、材料和统计口径变化都会影响 loss。','对。需要固定验证集与目标任务检查，还要控制其他训练条件。','重复是否有益取决于条件，不能用绝对结论代替评测。']},
 '5-budget':{question:'总预算固定，提高代码占比，会直接发生什么？',options:['一般文本的读取预算减少','模型参数一定增加','模型代码能力必然提高'],correct:0,explanations:['对。本例两类预算之和固定，给代码更多就给一般文本更少。','数据配比不直接决定参数规模。','能力变化必须通过实验测量，滑块只计算预算。']},
 '6-control':{question:'B 的验证 loss 比 A 低，但 B 的验证题更简单。能得出什么？',options:['B 的配方已被证明更好','要恢复相同评测条件才能公平比较','A 应立即停用'],correct:1,explanations:['改变了尺子，不能把差距归因于配方。','对。先分清变化来自模型还是评测材料。','现有证据不足以支持这种决策。']},
 '6-predict':{question:'留出实验偏离事先预测，下一步应该怎样？',options:['改写原预测，使它等于结果','保留预测，检查误差、实现与假设','忽略结果，趋势总会成立'],correct:1,explanations:['这会丢失检验预测能力的依据。','对。预测是待检验假设；偏差也是有价值的信息。','外推不保证成立，尤其在规模或配方发生变化时。']},
 '6-launch':{question:'小模型的对照实验更好，能证明大规模训练的恢复机制可靠吗？',options:['能，loss 低意味着系统没问题','不能，恢复需要独立演练','能，只要参数足够多'],correct:1,explanations:['模型指标和故障恢复回答不同的问题。','对。用真实的保存、中断和恢复过程检查系统。','参数数量无法替代恢复证据。']}
});
function prepSection(n,title,body){return `<section class="unit-section"><div class="unit-section-heading"><span>0${n} / ${['','先建立直觉','动手拆解','再深一层','做一次判断','检查理解'][n]||'继续理解'}</span><h2>${title}</h2></div>${body}</section>`}
function prepQuiz(id){return prepSection(5,'用你的判断，把这一课收好。',Object.keys(unitQuestions).filter(k=>k.startsWith(id+'-')).map(unitQuestion).join('')+`<details class="answer-explanation"><summary>这一课的判断依据</summary><p>${lessonReadings[id].takeaway}</p></details>`)}
function lesson4Body(){return prepSection(1,'给模型的“课本”，起初并不像课本。',`<p>第三课解释了文字怎样变成数字。现在把时间往前拨：网页下载下来时，正文常和导航、广告混在一起；同一内容可能出现在许多网站。模型学习什么，也取决于团队把哪些文字送到入口。</p><p>假设我们继续做一个解释代码的助手。下面这批<strong>本站编写的 8 条材料</strong>同时包含科普、代码、生活问答与噪声。先预测每一步会改变什么，再点击流程。</p><div class="unit-callout"><strong>先写一张材料登记卡</strong><p>来源是什么？何时取得？使用条件是什么？为什么符合训练目标？经过哪些处理？这些记录便于复查与复现。能下载到，不等于已经完成使用条件的核查。</p></div>`)+prepSection(2,'四步整理：每一步解决不同问题。',`<div class="unit-lab"><div class="lab-caption"><span>材料整理台 · 点击四个步骤</span><span>固定教学样本，不处理你的文件</span></div><div id="prep-pipeline">${prepPipeline()}</div></div><p>这里的过滤与去重判断已经写在教学样本中。真实流水线需要实现规则、评估误删，并保存处理版本。每完成一步，既看数量，也抽查保留下来和被排除的内容。</p>`)+prepSection(3,'把考卷分出去，还要防止答案绕回来。',`<p><strong>训练集</strong>用于更新参数；<strong>验证集</strong>帮助观察表现和选择方案；<strong>测试集</strong>留作相应的最终检查。反复根据测试结果修改方案，会削弱它作为独立检查的价值。</p><p>精确去重后还剩 A、C、D、G、H。A 和 C 是同一文章家族。如果只按文件拆分，就可能把改写版当成新题。切换下面的方式，看看绿色卡片去了哪里。</p><div class="unit-lab"><div class="lab-caption"><span>划分实验 · 已知相似家族为人工标注</span></div><div class="prep-toggle" role="group" aria-label="材料划分方式"><button data-prep-split="files" aria-pressed="${prepState.split==='files'}">按文件分开</button><button data-prep-split="family" aria-pressed="${prepState.split==='family'}">同一家族放同侧</button></div><div id="prep-split" aria-live="polite">${splitView()}</div></div><p>真实任务可能按文档、来源、时间或用户分组，并使用相似性检测。没有一个比例或去重阈值能通用于所有情况。本例仅演示重叠机制，没有建立真正的测试集。</p>`)+prepSection(4,'别让“干净”变成一种单一口音。',`<div class="worked-example"><h3>为什么保留 H 那条口语问答？</h3><p>“这台风扇咋不转？”不像百科，却是用户会问的问题。若只保留正式、长篇文字，数据可能丢掉实际问法。过滤应该围绕用途、可读性与内容有效性，检查不同语言和写作风格的覆盖。</p></div><div class="signal-cards"><article><h3>看保留样本</h3><p>有没有广告残留、乱码、断裂的代码或重复？</p></article><article><h3>看排除样本</h3><p>有用的短回答、口语、少见领域是否被误删？</p></article><article><h3>看处理记录</h3><p>同样输入与规则版本，能否得到可解释的结果？</p></article></div>`)+prepQuiz(4)}
function lesson5Body(){return prepSection(1,'库存多少，与这次读多少，是两回事。',`<p>上一课整理出可用材料。这一课要决定：有限的训练预算怎样分配？<strong>数据配比</strong>在这里指训练 token 预算中，各类材料预期占多少。</p><div class="signal-cards"><article><span class="signal-symbol">存</span><h3>可用语料</h3><p>仓库里去重后有多少材料。它描述库存。</p></article><article><span class="signal-symbol">取</span><h3>采样权重</h3><p>让某类材料更常被抽到。它影响读取机会。</p></article><article><span class="signal-symbol">读</span><h3>累计读取量</h3><p>训练实际读了多少 token。重复读也计入。</p></article></div><p>本文按 token 计量。若系统按文档采样，文档长短不同，文档比例不一定等于 token 比例；查看日志时要确认统计口径。</p>`)+prepSection(2,'亲手分一份有限的学习预算。',`<p>假设库存有 <strong>80 M 一般文本 token、20 M 代码 token</strong>（M 表示百万），tokenizer 固定。先猜：代码占比从 20% 调到 50%，哪些数字会变？</p><div class="unit-lab"><div class="lab-caption"><span>数据配方台 · 只计算分配，不预测能力</span><span>教学库存与预算</span></div><div class="prep-controls"><label for="prep-code">代码占比 <output id="prep-code-value">${prepState.code}%</output></label><input id="prep-code" type="range" min="0" max="100" step="10" value="${prepState.code}"><label for="prep-budget">总读取预算</label><select id="prep-budget">${[100,200,400].map(n=>`<option value="${n}" ${prepState.budget===n?'selected':''}>${n} M tokens</option>`).join('')}</select></div><div id="prep-mixture" aria-live="polite">${mixtureView()}</div></div><div class="worked-example"><h3>读懂 2.5 遍，而不是背住它</h3><p>在 100 M 总预算、50% 代码的方案里，代码读取量为 50 M。除以 20 M 代码库存，得到平均 2.5 遍。它是累计读取量与库存的比值，并不保证每个片段恰好读了相同次数。</p></div>`)+prepSection(3,'重复不产生新材料，也不必然等于浪费。',`<p>再次看到同一条材料仍可能提供训练信号；但增加读取量和增加独立内容不是同一件事。重复的收益与风险取决于材料、模型、训练长度和目标。</p><p>当一个小类别分到很高权重，要检查它被读了多少遍、是否过度记忆，以及固定验证集上是否还有改善。<strong>没有通用的“超过几遍就坏掉”界线</strong>，不能把某篇论文特定条件下的结果当成所有项目的规则。</p><div class="unit-callout"><strong>滑块没有告诉你“最佳比例”</strong><p>它只展示预算与重复曝光的算术关系。代码占比更高能否提高代码能力、会不会损害其他任务，需要真实训练和相同条件的评测。</p></div>`)+prepSection(4,'换了练习册，分数也可能换了含义。',`<div class="worked-example"><h3>训练 loss 从 2.8 降到 2.4</h3><p>这是一个假设场景：新配方含有更多容易预测的模板文字。训练 loss 下降，可能因为这次抽到的题更简单。它不能单独证明同一任务上的能力提高。</p></div><div class="prep-decision-flow"><div><strong>固定检查材料</strong><span>同一验证集、tokenizer 与评分方式</span></div><b aria-hidden="true">→</b><div><strong>控制其他条件</strong><span>相同模型与可比较的训练预算</span></div><b aria-hidden="true">→</b><div><strong>比较多项结果</strong><span>目标任务、其他能力与重复曝光</span></div></div><p>若代码题提高、一般文本表现下降，就记录这个取舍，再判断是否符合产品目标。下一课把这种判断组织成成本可控的小实验。</p>`)+prepQuiz(5)}
function lesson6Body(){return prepSection(1,'先用小实验，买到下一步的判断依据。',`<p>你已经有材料和候选配比。现在的问题是：要不要把设备和时间投入一次大训练？小实验先回答两个问题：<strong>系统能不能正确工作？这个方案有没有值得继续验证的优势？</strong></p><div class="signal-cards"><article><span class="signal-symbol">通</span><h3>先跑通</h3><p>小批数据能否进入模型？loss 是否有限？保存、评测与恢复能否执行？</p></article><article><span class="signal-symbol">比</span><h3>做对照</h3><p>尽量只改变要研究的因素，保留相同的衡量方式。</p></article><article><span class="signal-symbol">放</span><h3>逐级放大</h3><p>检查趋势是否持续，同时寻找更大规模才出现的问题。</p></article></div><p>一个很小的模型在很小的数据子集上学会拟合，可以作为实现检查；它不证明泛化好。小模型上的优势也只是该条件下的证据。</p>`)+prepSection(2,'先看是不是同一把尺，再看谁的数字低。',`<p>假设 A、B 使用不同的数据配比。每个预算档位的设置都预先固定，再比较同一列。切换到“有混杂的对照”，找出哪个条件悄悄变了。</p><div class="unit-lab"><div class="lab-caption"><span>实验记录台 · 编造数字用于判断练习</span><span>不是任何项目的训练结果</span></div><div class="prep-toggle" role="group" aria-label="实验比较条件"><button data-prep-trial="controlled" aria-pressed="${prepState.trial==='controlled'}">固定验证条件</button><button data-prep-trial="confounded" aria-pressed="${prepState.trial==='confounded'}">有混杂的对照</button></div><div id="prep-ladder">${ladderView()}</div></div>`)+prepSection(3,'Scaling ladder 是逐级验证，外推仍是假设。',`<p>真实的规模阶梯会选择一组模型大小、数据量或计算预算，记录可比较的运行结果。研究者可在明确的模型与数据范围内拟合趋势，再预测更大运行。不同设计控制的变量不同，要把配方和预算口径写清楚。</p><p>上面的三点算术只帮助理解“先预测、再检验”。真实拟合还要考虑噪声、函数形式、覆盖范围与预测误差。越远离已测范围，越需要谨慎；更换数据或模型结构后，也不能默认旧规律继续成立。</p><div class="worked-example"><h3>两种证据，别混成一句话</h3><p>“B 在这些小运行里更好”是已测条件内的比较；“B 在大规模也会更好”是尚待验证的推断。把后一句明确写成预测，给后续实验留下检验它的机会。</p></div>`)+prepSection(4,'效果看起来更好，系统也要准备好。',`<p>大规模会带来新的内存、通信和故障问题。假设你负责提出下一次扩大实验的建议，下面三类证据都需要检查。勾选代表你已理解需要什么证据，<strong>不会执行真实检查或启动训练</strong>。</p><div class="prep-gates">${gateItems.map(([key,title,note])=>`<label><input type="checkbox" data-prep-gate="${key}" ${prepState.gates[key]?'checked':''}><span><strong>${title}</strong><small>${note}</small></span></label>`).join('')}<p id="prep-gate-summary" role="status">${gateSummary()}</p></div><div class="unit-callout"><strong>一个可执行的建议，应该写清楚</strong><p>在哪些条件下观察到什么？还缺什么证据？下一次扩大到哪里？怎样评测？遇到什么异常要停止或回退？这比一句“曲线不错，直接上大模型”更能支持团队行动。</p></div>`)+prepQuiz(6)}
const prepLessonInfo={
 4:{title:'从杂乱网页，<br>到一份能解释来源的训练材料。',lead:'亲手走过提取、过滤与去重，再把学习材料和检查材料分开。理解数据准备为什么会影响后面的每一次判断。',goals:['区分提取正文、过滤、精确去重与近似重叠检查。','解释为什么不同文件仍可能泄漏相似内容。'],recap:'整理材料，也是在建立可信的检查方式。',bridge:'下一课：这些可用材料，各分到多少训练机会？',sources:[['https://arxiv.org/abs/2107.06499','Deduplicating Training Data：重复与训练／验证重叠']]},
 5:{title:'训练预算有限，<br>每一类材料该读多少？',lead:'拖动一份两类数据的配方，看清库存、采样比例与重复曝光。再判断：训练 loss 变低，究竟说明了什么？',goals:['计算一种材料的预期读取量与平均遍数。','区分预算变化与能力改善，知道怎样公平比较配方。'],recap:'配比是一项可检验的选择。',bridge:'下一课：先做小实验，为昂贵的大训练提供证据。',sources:[['https://arxiv.org/abs/2305.16264','Scaling Data-Constrained Language Models：数据重复的条件与收益']]},
 6:{title:'先花小成本，<br>验证值得放大的选择。',lead:'读一张小实验记录，识别不公平的比较。先写下预测，再看留出结果，最后补齐扩大训练前需要的证据。',goals:['区分受控对照、混杂因素、已测结果与预测。','说明为什么模型指标不能替代系统与恢复检查。'],recap:'材料 → 配比 → 小实验 → 下一步决策',bridge:'第二单元到这里连起来了。下一单元打开模型内部，看 Transformer 怎样利用这些输入。',sources:[['https://arxiv.org/abs/2001.08361','Scaling Laws for Neural Language Models：特定条件下的经验尺度规律'],['https://github.com/marin-community/marin','Marin：公开的训练、评测与基础设施实践']]}
};
function prepLesson(id){const info=prepLessonInfo[id];return `<main class="container"><div class="reader-grid">${readerSidebar(id)}<article class="unit-lesson prep-lesson self-contained-lesson"><div class="eyebrow">单元 2 · 训练之前，要准备什么 / 第 ${id} 课</div><h1 class="lesson-title">${info.title}</h1><p class="lesson-lead">${info.lead}</p><div class="unit-meta"><span>约 15–20 分钟 · 估计</span><span>图解 + 动手探索 + 理解检查</span></div><nav class="unit-journey" aria-label="第二单元学习路线">${['把材料整理好','把预算分清楚','用实验作判断'].map((label,i)=>`<a href="${cLink(i+4)}" data-go="${coursePage(i+4)}" ${id===i+4?'aria-current="step"':''}><span>0${i+4}</span><div>第 ${i+4} 课<strong>${label}</strong></div></a>`).join('')}</nav><div class="unit-objectives"><strong>这一课，你会解释</strong><ul>${info.goals.map(g=>`<li>${g}</li>`).join('')}</ul></div><div class="lesson-explanation">${({4:lesson4Body,5:lesson5Body,6:lesson6Body}[id])()}</div><section class="unit-recap"><span class="eyebrow">把这一课带走</span><h2>${info.recap}</h2><p>${lessonReadings[id].takeaway}</p><p>${info.bridge}</p></section>${coursePager(id)}<div class="lesson-supplements"><h2>继续深入（选读）</h2><details class="optional-reading"><summary>本课依据与演示边界</summary><p>本文为一般原理的原创教学解释。样本、库存、预算、loss 与预测结果均为教学假设，没有运行实际模型，也不代表 Marin 实测。下列来源支持相关概念，不验证本页演示数字。</p>${info.sources.map(([url,title])=>`<a class="source-link" href="${url}" target="_blank" rel="noopener noreferrer">${title} ↗</a>`).join('')}</details>${samePageMaterials(id)}</div></article></div></main>`}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;
 if(b.dataset.prepStage!==undefined){prepState.stage=Number(b.dataset.prepStage);$('#prep-pipeline').innerHTML=prepPipeline();document.querySelector(`[data-prep-stage="${prepState.stage}"]`)?.focus({preventScroll:true})}
 if(b.dataset.prepSplit){prepState.split=b.dataset.prepSplit;document.querySelectorAll('[data-prep-split]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.prepSplit===prepState.split)));$('#prep-split').innerHTML=splitView()}
 if(b.dataset.prepTrial){prepState.trial=b.dataset.prepTrial;prepState.revealed=false;document.querySelectorAll('[data-prep-trial]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.prepTrial===prepState.trial)));$('#prep-ladder').innerHTML=ladderView()}
 if(b.hasAttribute('data-reveal-ladder')){prepState.revealed=true;$('#prep-ladder').innerHTML=ladderView();document.querySelector('[data-reveal-ladder]')?.parentElement.setAttribute('tabindex','-1');document.querySelector('[data-reveal-ladder]')?.parentElement.focus({preventScroll:true})}
});
document.addEventListener('input',event=>{if(event.target.id==='prep-code'){prepState.code=Number(event.target.value);$('#prep-code-value').textContent=prepState.code+'%';$('#prep-mixture').innerHTML=mixtureView()}});
document.addEventListener('change',event=>{if(event.target.id==='prep-budget'){prepState.budget=Number(event.target.value);$('#prep-mixture').innerHTML=mixtureView()}if(event.target.dataset.prepGate){prepState.gates[event.target.dataset.prepGate]=event.target.checked;$('#prep-gate-summary').textContent=gateSummary()}});
